//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_WebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEmp
    {
        //public int EmpID { get; set; }
        //public string Name { get; set; }
        //public string City { get; set; }
        //public string MobileNo { get; set; }
        //public Nullable<System.DateTime> birthdate { get; set; }
        //public string Email { get; set; }

        [Display(Name = "EmployeeId")]
        public int EmpID { get; set; }
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Display(Name = "City")]
        public string City { get; set; }
        [Display(Name = "Contact No")]
        public string MobileNo { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> birthdate { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}
